# Generated by Django 3.2.2 on 2021-05-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_description', models.CharField(max_length=300)),
                ('article', models.TextField(blank=True)),
                ('parution_deadline', models.DateTimeField(verbose_name='published date')),
                ('article_access', models.BooleanField(default=True)),
            ],
        ),
    ]
